### ISSUE TITLE
VRRP support

### ISSUE THREAD

**Issue by Harliff** [vyos/vyos.vyos#152]
##### SUMMARY

Add support for VRRP configuration

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

It could be named "vyos.vyos.vyos_vrrp" 

##### ADDITIONAL INFORMATION

It would be nice to configure VRRP using an dedicated ansible module, not only via vyos.vyos.vyos_config.
Please see example task below - would it be hard to implement it as a module?

```yaml
---
# add a vif interface with description (without static address), then configure vrrp for them
- name: configure vrrp for vlan {{ vlan }} on '{{ inventory_hostname }}' router
  vyos.vyos.vyos_config:
    lines:
      - set interfaces {{ router_main_interface_type }} {{ router_main_interface }} vif {{ vlan }} description '{{ vlan_description }}'
      - set high-availability vrrp group VLAN-{{ vlan }} description '{{ vlan_description }}'
      - set high-availability vrrp group VLAN-{{ vlan }} hello-source-address '{{ router_hello_source_address }}'
      - set high-availability vrrp group VLAN-{{ vlan }} interface '{{ router_main_interface}}.{{ vlan }}'
      - set high-availability vrrp group VLAN-{{ vlan }} priority '{{ router_vrrp_priority }}'
      - set high-availability vrrp group VLAN-{{ vlan }} virtual-address '{{ router_interface_ip }}/{{ mask_bits }}'
      - set high-availability vrrp group VLAN-{{ vlan }} vrid '{{ vrid }}'

```
