### ISSUE TITLE
Support configuring area interfaces for OSPFv3

### ISSUE THREAD

**Issue by devon-mar** [vyos/vyos.vyos#176]
##### SUMMARY

Add support for OSPFv3 area interface configuration.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`vyos.vyos.vyos_ospfv3`

##### ADDITIONAL INFORMATION

Task:
```yaml
- vyos.vyos.vyos_ospfv3:
    config:
      areas:
        - area_id: "0"
          interfaces:
            - eth0
            - lo
    state: present
```
Desired config:
```
[edit protocols ospfv3]
vyos@BH-NET-FR01# show
 area 0 {
     interface eth0
     interface lo
 }
```
