### ISSUE TITLE
[Firewall] Manage bonding interface for Rule-Set 

### ISSUE THREAD

**Issue by emferrandi** [vyos/vyos.vyos#219]
##### SUMMARY

Add interface firewalling for bonding interface 

In the module, it's impossible to chose _interface ethernet_ or _interface bonding_ 

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

Module : vyos.vyos.vyos_firewall_interfaces (https://github.com/ansible-collections/vyos.vyos/blob/main/docs/vyos.vyos.vyos_firewall_interfaces_module.rst#vyosvyosvyos_firewall_interfaces)

##### ADDITIONAL INFORMATION

When I run vyos.vyos, the module always run this command : 

`set interfaces ethernet bond0 firewall in name test`

Instead of : 
`set interfaces bonding bond0 firewall in name test`

##### TEST

Configuration : 
```yaml
bonding bond0 {
     address 192.168.0.254/24
     hash-policy layer2+3
     member {
         interface eth2
         interface eth3
     }
 }
 ethernet eth0 {
     address dhcp
 }
```

Yaml for test :
```yaml
- name: Merge the provided configuration with the existing running configuration
  vyos.vyos.vyos_firewall_interfaces:
    config: 
    - name: bond0
      access_rules:
      - afi: ipv4
        rules:
        - name: fromINTERNET_ipv4
          direction: in
        - name: toINTERNET_ipv4
          direction: out
        - name: toLOCAL_ipv4
          direction: local    
    state: merged
```
