### ISSUE TITLE
vyos_bgp_global setting neighbor passive causes module to try configuring neighbhr next-hop-self

### ISSUE THREAD

**Issue by rbh1981** [vyos/vyos.vyos#269]
<!--- Verify first that your issue is not already reported on GitHub -->
<!--- Also test if the latest release and devel branch are affected too -->
<!--- Complete *all* sections as described, this form is processed automatically -->

##### SUMMARY
<!--- Explain the problem briefly below -->
When using module vyos_bgp_global to configure neighbor as passive it causes ansible to try configuring 'neighbor <address> nexthop-self'. Commenting out the passive variable allows play to execute properly (but not set passive neighbor config).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below, use your best guess if unsure -->
vyos_bgp_global

##### ANSIBLE VERSION
<!--- Paste verbatim output from "ansible --version" between quotes -->
```paste below
ansible [core 2.12.7]
  config file = /home/xxxxxx/xxxxxx/ansible.cfg
  configured module search path = ['/home/xxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/xxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
vyos.vyos  2.8.0  

```

##### CONFIGURATION
<!--- Paste verbatim output from "ansible-config dump --only-changed" between quotes -->
```paste below
DEFAULT_GATHERING(/home/xxxx/xxxx/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/home/xxxx/xxxxx/ansible.cfg) = ['/home/xxxx/xxxx/hosts.yml']
DISPLAY_SKIPPED_HOSTS(/home/xxxx/xxxx/ansible.cfg) = False
HOST_KEY_CHECKING(/home/xxxx/xxxx/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/xxxx/xxxx/ansible.cfg) = 30
PERSISTENT_CONNECT_TIMEOUT(/home/xxxx/xxxx/ansible.cfg) = 60

```

##### OS / ENVIRONMENT
<!--- Provide all relevant information below, e.g. target OS versions, network device firmware, etc. -->
Ubuntu Server 20.04 on Azure

##### STEPS TO REPRODUCE
<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->
Run ansible play trying to set neighbor passive and ansible will error out

<!--- Paste example playbooks or commands between quotes below -->
```yaml
# Ansible play
- name: "Configure BGP Global"
  vyos.vyos.vyos_bgp_global:
    config: "{{ bgp_global }}"

# bgp_global host variable file
bgp_global:
  as_number: 64555
  bgp_params:
    default:
      no_ipv4_unicast: true
    router_id: 10.1.1.1
    log_neighbor_changes: true
  neighbor:
    - address: 10.240.10.20
      passive: true
      remote_as: 64555
    - address: 10.240.10.30
      passive: true
      remote_as: 64555
    - address: 10.240.10.40
      passive: true
      remote_as: 64555

```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- Describe what you expected to happen when running the steps above -->
bgp_global moduel should configure specified neighbor as passive:

set protocols bgp 64555 neighbor 10.240.10.40 passive

##### ACTUAL RESULTS
<!--- Describe what actually happened. If possible run with extra verbosity (-vvvv) -->
Ansible tries to configure neighbor <address> nexthop-self. 
<!--- Paste verbatim command output between quotes -->
```paste below
ansible.module_utils.connection.ConnectionError: set protocols bgp 64555 neighbor 10.240.10.40 nexthop-self                                                                                                                                                                                                                                     
  Configuration path: protocols bgp 64555 neighbor 10.240.10.40 [nexthop-self] is not valid                                                                             
  Set failed                                                                                                                                                            
                        
```
