### ISSUE TITLE
Add replace configuration for module vyos_config

### ISSUE THREAD

**Issue by fett0** [vyos/vyos.vyos#288]
##### SUMMARY

We have many cases when creates automation deployments/uses cases, where we have the necessity to replace full configuration , I've seen in other modules that have this ability (https://docs.ansible.com/ansible/latest/collections/cisco/iosxr/iosxr_config_module.html#parameter-replace) it will be useful to get it for vyos_config module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

  vyos.vyos.vyos_config

##### ADDITIONAL INFORMATION

```yaml
example : https://docs.ansible.com/ansible/latest/collections/cisco/iosxr/iosxr_config_module.html#parameter-replace

```

```
- name: load a config from file/disk and replace the current config
  vyos.vyos.vyos_config:
    src: vyos.cfg
    replace: config
    backup: yes
```
