### ISSUE TITLE
vyos_lag_interfaces is using incorrect bond members cli commands

### ISSUE THREAD

**Issue by Nenq** [vyos/vyos.vyos#298]
##### SUMMARY

Module vyos_lag_interfaces is trying to add members via incorrect cli commands. Current syntax looks like this: https://docs.vyos.io/en/equuleus/configuration/interfaces/bonding.html#member-interfaces

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vyos_lag_interfaces 

##### ANSIBLE VERSION

```
ansible [core 2.12.4]
  config file = /ansible/ansible.cfg
  configured module search path = ['/ansible/modules']
  ansible python module location = /home/ansible/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  jinja version = 2.11.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/ansible/.ansible/collections/ansible_collections
Collection Version
---------- -------
vyos.vyos  4.0.1

# /home/ansible/.local/lib/python3.8/site-packages/ansible_collections
Collection Version
---------- -------
vyos.vyos  2.6.0

# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection Version
---------- -------
vyos.vyos  3.0.1
```

##### OS / ENVIRONMENT

VyOS 1.3.2

##### STEPS TO REPRODUCE

Execute a task using vyos_lag_interfaces module which sets bond members

```
- name: Merge provided configuration with device configuration
  vyos.vyos.vyos_lag_interfaces:
    config:
    - name: bond0
      mode: 802.3ad
      members:
      - member: eth0
      - member: eth1
      hash_policy: layer3+4

```

##### EXPECTED RESULTS

Adds ethernet member to the bond using correct commands:  set interfaces bonding bond0 member interface eth0

##### ACTUAL RESULTS

```
fatal: [test-coret01]: FAILED! => {
    "changed": false,
    "module_stderr": "set interfaces ethernet eth0 bond-group 'bond0'\r\n\r\n  Configuration path: interfaces ethernet eth0 [bond-group] is not valid\r\n  Set failed\r\n\r\n[edit]\r\r\nansible@test-corert01# ",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}

```
