### ISSUE TITLE
Configuration path: system [ntp] is not valid

### ISSUE THREAD

**Issue by timherrm** [vyos/vyos.vyos#339]
##### SUMMARY

I am trying to configure an NTP server on an VyOS router. I copied the example from the ntp_global module and edited it to meet my environment.

On VyOS 1.3 this is working as the command to set ntp-servers is: `set system ntp`
On VyOS 1.5 the command to set ntp-servers is: `set service ntp`

Because of this change the playbook fails.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vyos.vyos.vyos_ntp_global

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.8]
  python version = 3.9.6 (default, Nov 10 2023, 13:38:27) [Clang 15.0.0 (clang-1500.1.0.2.5)]
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection Version
---------- -------
vyos.vyos  4.1.0  
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

```
vyos@vyos:~$ show version
Version:          VyOS 1.5-rolling-202401240024
Release train:    current

Built by:         autobuild@vyos.net
Built on:         Wed 24 Jan 2024 02:18 UTC
Build UUID:       8e846105-cd9d-4530-8ead-7e917dc2ef37
Build commit ID:  6c6a5856122790

Architecture:     x86_64
Boot via:         installed image
System type:      KVM guest
```

##### STEPS TO REPRODUCE

```yaml
    - name: Replace the existing ntp config with the new config
      vyos.vyos.vyos_ntp_global:
        config:
            servers:
              - server: "{{ntp1_ip}}"
              - server: "{{ntp2_ip}}"
        state: replaced
```

##### EXPECTED RESULTS

NTP-server is set to the given IP

##### ACTUAL RESULTS

```paste below
fatal: [host_vyos]: FAILED! => changed=false 
  module_stderr: |-
    set system ntp server REDACTED
  
      Configuration path: system [ntp] is not valid
      Set failed
  
    [edit]
    vyos@vyos#
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
```
