### ISSUE TITLE
LAG interfaces module is outdated

### ISSUE THREAD

**Issue by aaronmehar** [vyos/vyos.vyos#356]
The module to creae LAG interfaces needs updating as it's using an old CLI syntax from 1.1 days

I have a playbook using this task
```yaml
- name: Create bond interfaces
  vyos.vyos.vyos_lag_interfaces:
    config:
      - name: "{{ item.name }}"
        mode: "{{ item.mode }}"
        members:
          - member: "{{ item.members[0] }}"
          - member: "{{ item.members[1] }}"
        hash_policy: "{{ item.hash_policy }}"
  when: item.members is defined
  loop: "{{ lag_interfaces }}"
```

but it errors out with this error
```yaml
  module_stderr: |-
    set interfaces ethernet eth0 bond-group 'bond0'

      Configuration path: interfaces ethernet eth0 [bond-group] is not valid
      Set failed
```
